# command to select language
language: python

# command to install dependencies
install:
  - pip install -r requirements.txt
  
# command to run tests
script:
  - SET FLASK_APP=main.py
  - flask run
  - pytest test.py
